services:

  server:
    env_file:
      "./server/.env"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: chorekeeper/chorekeeper-express-backend:latest
    # image: "chorekeeper-express-backend"
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: chorekeeper/chorekeeper-react-frontend:latest
    # image: "chorekeeper-react-frontend"
    ports:
      - "3000:3000"