name: Assign reviewers to pull request
run-name: Auto assign reviewers

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Add Reviewers
      uses: AveryCameronUofR/add-reviewer-gh-action@1.0.3 #madrapps/add-reviewers@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        reviewers: Ahsen19